CREATE USER USER_1 IDENTIFIED BY 123;

GRANT ALL PRIVILEGES ON example_table TO USER_1;

GRANT ALL PRIVILEGES TO USER_1;

--1 

CREATE TABLE example_table (
  id NUMBER PRIMARY KEY,
  name VARCHAR2(50)
  )
  
  
  
--2 
INSERT INTO example_table (id, name)
VALUES (1, 'John');

INSERT INTO example_table (id, name)
VALUES (2, 'Jane');

INSERT INTO example_table (id, name)
VALUES (3, 'Tom');

INSERT INTO example_table (id, name)
VALUES (4, 'Mary');

INSERT INTO example_table (id, name)
VALUES (5, 'Bob');

INSERT INTO example_table (id, name)
VALUES (6, 'Samantha');

INSERT INTO example_table (id, name)
VALUES (7, 'Peter');

INSERT INTO example_table (id, name)
VALUES (8, 'Emily');

INSERT INTO example_table (id, name)
VALUES (9, 'David');

INSERT INTO example_table (id, name)
VALUES (10, 'Lisa');
 
  
--3


CREATE OR REPLACE TRIGGER INSERT_TRIGGER_EXAMPLE_TABLE 
BEFORE INSERT ON EXAMPLE_TABLE
BEGIN
DBMS_OUTPUT.PUT_LINE('INSERT TABLE EXAMPLE_TABLE');
END;

CREATE OR REPLACE TRIGGER UPDATE_TRIGGER_EXAMPLE_TABLE
BEFORE UPDATE ON EXAMPLE_TABLE
BEGIN
DBMS_OUTPUT.PUT_LINE('UPDATE TABLE EXAMPLE');
END;


CREATE OR REPLACE TRIGGER DELETE_TRIGGER_EXAMPLE_TABLE
BEFORE DELETE ON EXAMPLE_TABLE
BEGIN
DBMS_OUTPUT.PUT_LINE('DELETE TABLE EXAPMLE');
END;




--4


CREATE OR REPLACE TRIGGER INSERT_TRIGGER_EXAMPLE_TABLE_ROW 
BEFORE INSERT ON EXAMPLE_TABLE
FOR EACH ROW
BEGIN
DBMS_OUTPUT.PUT_LINE('INSERT TABLE EXAMPLE_TABLE ROW');
END;

CREATE OR REPLACE TRIGGER UPDATE_TRIGGER_EXAMPLE_TABLE_ROW
BEFORE UPDATE ON EXAMPLE_TABLE
FOR EACH ROW
BEGIN
DBMS_OUTPUT.PUT_LINE('UPDATE TABLE EXAMPLE ROW');
END;


CREATE OR REPLACE TRIGGER DELETE_TRIGGER_EXAMPLE_TABLE_ROW
BEFORE DELETE ON EXAMPLE_TABLE
FOR EACH ROW
BEGIN
DBMS_OUTPUT.PUT_LINE('DELETE TABLE EXAPMLE ROW');
END;


--5

CREATE OR REPLACE TRIGGER TRIGGER_PREDICATE
BEFORE INSERT OR UPDATE OR DELETE ON EXAMPLE_TABLE
BEGIN
     IF INSERTING THEN DBMS_OUTPUT.PUT_LINE('INSERTING TABLE');
     ELSIF UPDATING THEN DBMS_OUTPUT.PUT_LINE('UPDATING TABLE');
     ELSIF DELETING THEN DBMS_OUTPUT.PUT_LINE('DELETING TABLE');        
     END IF;
END;


--6

CREATE OR REPLACE TRIGGER TRIGGER_AFTER
AFTER INSERT OR UPDATE OR DELETE ON EXAMPLE_TABLE
BEGIN
     IF INSERTING THEN DBMS_OUTPUT.PUT_LINE('INSERTING TABLE');
     ELSIF UPDATING THEN DBMS_OUTPUT.PUT_LINE('UPDATING TABLE');
     ELSIF DELETING THEN DBMS_OUTPUT.PUT_LINE('DELETING TABLE');        
     END IF;
END;


--7

CREATE OR REPLACE TRIGGER INSERT_TRIGGER_EXAMPLE_TABLE_ROW_AFTER 
BEFORE INSERT ON EXAMPLE_TABLE
FOR EACH ROW
BEGIN
DBMS_OUTPUT.PUT_LINE('INSERT TABLE EXAMPLE_TABLE ROW AFTER');
END;

CREATE OR REPLACE TRIGGER UPDATE_TRIGGER_EXAMPLE_TABLE_ROW_AFTER
BEFORE UPDATE ON EXAMPLE_TABLE
FOR EACH ROW
BEGIN
DBMS_OUTPUT.PUT_LINE('UPDATE TABLE EXAMPLE ROW AFTER');
END;


CREATE OR REPLACE TRIGGER DELETE_TRIGGER_EXAMPLE_TABLE_ROW_AFTER
BEFORE DELETE ON EXAMPLE_TABLE
FOR EACH ROW
BEGIN
DBMS_OUTPUT.PUT_LINE('DELETE TABLE EXAPMLE ROW AFTER');
END;


--8
    create table AUDIT_
    (
        OPERATIONDATE timestamp, 
        OPERATIONTYPE varchar2(50), 
        TRIGGERNAME varchar2(30),
        DATA varchar2(300)   
    );
    
    
--9


CREATE OR REPLACE TRIGGER INSERT_TRIGGER_EXAMPLE_TABLE
BEFORE INSERT ON EXAMPLE_TABLE
FOR EACH ROW
BEGIN
  INSERT INTO AUDIT_ (OperationDate, OperationType, TriggerName, Data)
  VALUES (SYSTIMESTAMP, 'INSERT', 'INSERT_TRIGGER_EXAMPLE_TABLE', :NEW.id || ', ' || :NEW.name);
END;

CREATE OR REPLACE TRIGGER UPDATE_TRIGGER_EXAMPLE_TABLE
BEFORE UPDATE ON EXAMPLE_TABLE
FOR EACH ROW
BEGIN
  INSERT INTO AUDIT_ (OperationDate, OperationType, TriggerName, Data)
  VALUES (SYSTIMESTAMP, 'UPDATE', 'UPDATE_TRIGGER_EXAMPLE_TABLE', :OLD.id || ', ' || :OLD.name || ' -> ' || :NEW.id || ', ' || :NEW.name);
END;

CREATE OR REPLACE TRIGGER DELETE_TRIGGER_EXAMPLE_TABLE
BEFORE DELETE ON EXAMPLE_TABLE
FOR EACH ROW
BEGIN
  INSERT INTO AUDIT_ (OperationDate, OperationType, TriggerName, Data)
  VALUES (SYSTIMESTAMP, 'DELETE', 'DELETE_TRIGGER_EXAMPLE_TABLE', :OLD.id || ', ' || :OLD.name);
END;

-- 10

INSERT INTO example_table (id, name) VALUES (1, 'John');
DELETE EXAMPLE_TABLE WHERE ID =11;



--11
CREATE OR REPLACE TRIGGER prevent_drop_table
BEFORE DROP ON DATABASE
DECLARE
  v_object_type VARCHAR2(30);
BEGIN
  SELECT object_type INTO v_object_type
  FROM user_objects
  WHERE object_name = 'EXAMPLE_TABLE';
  
  IF v_object_type = 'TABLE' THEN
    RAISE_APPLICATION_ERROR(-20001, 'Table EXAMPLE_TABLE cannot be dropped');
  END IF;
END;

  drop table EXAMPLE_TABLE;
  
  --12
  
  drop table AUDIT_;
  
  
  --13 
  
  create view view_test as SELECT * FROM example_table;
  
  
    create or replace trigger TRIGGER_INSTEAD_OF_INSERT
    instead of insert on view_test
    begin
        if INSERTING then
            DBMS_OUTPUT.PUT_LINE('Instead of Update trigger called.');
         INSERT INTO example_table (id, name)
VALUES (11, 'Bo1b');
        end if;
    end TRIGGER_INSTEAD_OF_INSERT;



    insert into view_test values(12, 'וףûו');
    select * from view_test;