/*7. Разработать два сценария A и B на примере базы данных X_UNIVER. 
Сценарий A представляет собой явную транзакцию с уровнем изолированности SERIALIZABLE. 
Сценарий B – явную транзакцию с уровнем изолированности READ COMMITED.
Сценарий A должен демонстрировать отсутствие фантомного, неподтвержденного и неповторяющегося
чтения.
*/
USE UNIVER;


SET TRANSACTION ISOLATION LEVEL SERIALIZABLE 
BEGIN TRANSACTION 
DELETE AUDITORIUM WHERE AUDITORIUM = '123-4'
INSERT AUDITORIUM VALUES ('123-4', 'ЛК', 10, '123-1')
UPDATE AUDITORIUM SET AUDITORIUM_NAME = '123-4' WHERE AUDITORIUM = '123-4'
SELECT AUDITORIUM FROM AUDITORIUM WHERE AUDITORIUM = '123-4'
--------T1---------
SELECT AUDITORIUM FROM AUDITORIUM WHERE AUDITORIUM = '123-4'
--------T2---------
COMMIT 	


SELECT * FROM AUDITORIUM


--- B ---	
BEGIN TRANSACTION 	  
DELETE AUDITORIUM WHERE AUDITORIUM = '123-4' 
INSERT AUDITORIUM VALUES ('123-4', 'ЛК', 10, '123-1')
UPDATE AUDITORIUM SET AUDITORIUM_NAME = '123-4' WHERE AUDITORIUM = '123-4'
SELECT AUDITORIUM FROM AUDITORIUM  WHERE AUDITORIUM = '123-4'
--------T1---------
COMMIT
SELECT AUDITORIUM FROM AUDITORIUM  WHERE AUDITORIUM = '123-4'
--------T2---------

--- B ---	
BEGIN TRANSACTION 	  
DELETE AUDITORIUM WHERE AUDITORIUM = '123-4' 
INSERT AUDITORIUM VALUES ('123-4', 'ЛК', 10, '123-1')
UPDATE AUDITORIUM SET AUDITORIUM_NAME = '123-4' WHERE AUDITORIUM = '123-4'
SELECT AUDITORIUM FROM AUDITORIUM  WHERE AUDITORIUM = '123-4'
--------T1---------
COMMIT
SELECT AUDITORIUM FROM AUDITORIUM  WHERE AUDITORIUM = '123-4'
--------T2---------