/*8. Разработать сценарий, де-монстрирующий свойства вло-женных транзакций,
на примере базы данных X_UNIVER. */

USE UNIVER;

BEGIN TRAN
	INSERT AUDITORIUM_TYPE VALUES ('TEST', 'TEST TEST');
	BEGIN TRAN
		UPDATE AUDITORIUM SET AUDITORIUM = '206-1' WHERE AUDITORIUM_TYPE = 'TEST'
		COMMIT
		IF @@TRANCOUNT > 0 ROLLBACK
	SELECT
		(SELECT COUNT(*) FROM AUDITORIUM WHERE AUDITORIUM_TYPE='TEST') 'AUDIT',
		(SELECT COUNT(*) FROM AUDITORIUM_TYPE  WHERE AUDITORIUM_TYPE='TEST') 'TYPE'
DELETE  AUDITORIUM_TYPE WHERE  AUDITORIUM_TYPE = 'TEST'; 