/*4. Разработать сценарий, демонстри-рующий свойства навигации в резуль-тирующем наборе 
курсора с атрибутом SCROLL на примере базы данных X_UNIVER.
Использовать все известные ключе-вые слова в операторе FETCH.
*/
DECLARE @TYPE NVARCHAR(20), @CAPACITY NVARCHAR(20)
DECLARE LOCAL CURSOR GLOBAL STATIC SCROLL FOR SELECT AUDITORIUM_TYPE, AUDITORIUM_CAPACITY FROM AUDITORIUM

OPEN LOCAL
PRINT 'ВСЕ: '
FETCH LOCAL INTO @TYPE, @CAPACITY
WHILE @@FETCH_STATUS = 0
BEGIN
PRINT '' + @TYPE + ' ' + @CAPACITY
FETCH LOCAL INTO @TYPE, @CAPACITY
END
CLOSE LOCAL

OPEN LOCAL
PRINT 'ПЕРВАЯ СТРОКА: '
FETCH FIRST FROM LOCAL INTO @TYPE, @CAPACITY
PRINT '' + @TYPE + @CAPACITY

PRINT 'ВТОРАЯ СТРОКА (ABSOLUTE)'
FETCH ABSOLUTE 2 FROM LOCAL INTO @TYPE, @CAPACITY
PRINT '' + @TYPE + @CAPACITY

PRINT 'ПЯТАЯ СТРОКА С КОНЦА (ABSOLUTE)'
FETCH ABSOLUTE -5 FROM LOCAL INTO @TYPE, @CAPACITY
PRINT '' + @TYPE + @CAPACITY

PRINT 'ВТОРАЯ СТРОКА (RELATIVE)'
FETCH RELATIVE 2 FROM LOCAL INTO @TYPE, @CAPACITY
PRINT '' + @TYPE + @CAPACITY

PRINT 'СЛЕДУЮЩАЯ СТРОКА: '
FETCH NEXT FROM LOCAL INTO @TYPE, @CAPACITY
PRINT '' + @TYPE + @CAPACITY

PRINT 'ПРЕДШЕВСТВУЮЩАЯ СТРОКА: '
FETCH PRIOR FROM LOCAL INTO @TYPE, @CAPACITY
PRINT '' + @TYPE + @CAPACITY

PRINT 'ПОСЛЕДНЯЯ СТРОКА: '
FETCH LAST FROM LOCAL INTO @TYPE, @CAPACITY
PRINT '' + @TYPE + @CAPACITY

CLOSE LOCAL
