
/*Разработать SELECT-запрос, с помо-щью которого из таблицы PROGRESS удаляются строки, содержащие ин-формацию о студентах, 
получивших оценки ниже 4 (использовать объеди-нение таблиц PROGRESS, STUDENT, GROUPS). */

USE UNIVER;
DECLARE @NOTE INT, @NAME NVARCHAR(50), @FACULTY NVARCHAR(20);
DECLARE GOODBYE CURSOR DYNAMIC GLOBAL FOR
SELECT PROGRESS.NOTE, STUDENT.NAME, GROUPS.FACULTY
FROM PROGRESS 
JOIN STUDENT ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
JOIN GROUPS ON STUDENT.IDGROUP = GROUPS.IDGROUP
OPEN GOODBYE
FETCH GOODBYE INTO @NOTE, @NAME, @FACULTY
WHILE @@FETCH_STATUS = 0
BEGIN
PRINT 'ОЦЕНКА ' + CAST(@NOTE AS NVARCHAR(10)) + ' - ' + @NAME + ' - ' + @FACULTY
FETCH GOODBYE INTO @NOTE, @NAME, @FACULTY

IF @NOTE <4
DELETE PROGRESS WHERE CURRENT OF GOODBYEE
END
CLOSE GOODBYE



---------------------------------------
---------------BANK--------------------
---------------------------------------

USE BANK;
GO 
DECLARE @СТАВКА INT, @NAME NVARCHAR(50);
DECLARE MY_TEST_6 CURSOR DYNAMIC GLOBAL FOR
SELECT СТАВКА, Назаание_кредита
FROM БАНК
OPEN MY_TEST_6
FETCH MY_TEST_6 INTO @СТАВКА, @NAME
WHILE @@FETCH_STATUS = 0
BEGIN
PRINT 'СТАВКА ' + CAST(@СТАВКА AS NVARCHAR(10)) + ' - ' + @NAME 
FETCH MY_TEST_6 INTO @СТАВКА, @NAME

IF @СТАВКА =3 
DELETE БАНК WHERE CURRENT OF MY_TEST_6
END
CLOSE MY_TEST_6

DEALLOCATE  MY_TEST_6



