/*7. Разработать курсоры для базы данных X_MyBASE и продемонстрировать их работу. */
USE BANK;
DECLARE @NAME VARCHAR(20)
DECLARE LOCAL CURSOR GLOBAL STATIC SCROLL FOR
SELECT НАЗААНИЕ_КРЕДИТА FROM БАНК
OPEN LOCAL
PRINT 'ВСЕ: '
FETCH LOCAL INTO @NAME
WHILE @@FETCH_STATUS = 0
BEGIN
PRINT '' + @NAME
FETCH LOCAL INTO @NAME
END
CLOSE LOCAL

OPEN LOCAL
PRINT 'ПЕРВАЯ СТРОКА: '
FETCH FIRST FROM LOCAL INTO @NAME
PRINT @NAME

PRINT 'ВТОРАЯ СТРОКА (ABSOLUTE)'
FETCH ABSOLUTE 2 FROM LOCAL INTO @NAME
PRINT @NAME

PRINT 'ПЯТАЯ СТРОКА С КОНЦА (ABSOLUTE)'
FETCH ABSOLUTE -5 FROM LOCAL INTO @NAME
PRINT @NAME

PRINT 'ВТОРАЯ СТРОКА (RELATIVE)'
FETCH RELATIVE 2 FROM LOCAL INTO @NAME
PRINT @NAME

PRINT 'СЛЕДУЮЩАЯ СТРОКА: '
FETCH NEXT FROM LOCAL INTO @NAME
PRINT @NAME

PRINT 'ПРЕДШЕВСТВУЮЩАЯ СТРОКА: '
FETCH PRIOR FROM LOCAL INTO @NAME
PRINT @NAME

PRINT 'ПОСЛЕДНЯЯ СТРОКА: '
FETCH LAST FROM LOCAL INTO @NAME
PRINT @NAME

CLOSE LOCAL