/*4. Разработать сценарий, демонстри-рующий свойства навигации в резуль-тирующем наборе 
курсора с атрибутом SCROLL на примере базы данных X_UNIVER.
Использовать все известные ключе-вые слова в операторе FETCH.
*/

DECLARE @TYPE NVARCHAR(20), @CAPACITY NVARCHAR(20)
DECLARE PRIMER_4 CURSOR GLOBAL STATIC SCROLL 
FOR SELECT AUDITORIUM_TYPE, AUDITORIUM_CAPACITY FROM AUDITORIUM

OPEN PRIMER_4
PRINT 'ВСЕ: '
FETCH PRIMER_4 INTO @TYPE, @CAPACITY
WHILE @@FETCH_STATUS = 0
BEGIN
PRINT '' + @TYPE + ' ' + @CAPACITY
FETCH PRIMER_4 INTO @TYPE, @CAPACITY
END
CLOSE PRIMER_4

OPEN PRIMER_4
PRINT 'ПЕРВАЯ СТРОКА: '
FETCH FIRST FROM PRIMER_4 INTO @TYPE, @CAPACITY
PRINT '1' + @TYPE + @CAPACITY

PRINT 'ВТОРАЯ СТРОКА (ABSOLUTE)'
FETCH ABSOLUTE 2 FROM PRIMER_4 INTO @TYPE, @CAPACITY
PRINT '2' + @TYPE + @CAPACITY

PRINT 'ПЯТАЯ СТРОКА С КОНЦА (ABSOLUTE)'
FETCH ABSOLUTE -5 FROM PRIMER_4 INTO @TYPE, @CAPACITY
PRINT '3' + @TYPE + @CAPACITY

PRINT 'ВТОРАЯ СТРОКА (RELATIVE)'
FETCH RELATIVE 2 FROM PRIMER_4 INTO @TYPE, @CAPACITY
PRINT '' + @TYPE + @CAPACITY

PRINT 'СЛЕДУЮЩАЯ СТРОКА: '
FETCH NEXT FROM LOCAL INTO @TYPE, @CAPACITY
PRINT '' + @TYPE + @CAPACITY

PRINT 'ПРЕДШЕВСТВУЮЩАЯ СТРОКА: '
FETCH PRIOR FROM PRIMER_4 INTO @TYPE, @CAPACITY
PRINT '' + @TYPE + @CAPACITY

PRINT 'ПОСЛЕДНЯЯ СТРОКА: '
FETCH LAST FROM PRIMER_4 INTO @TYPE, @CAPACITY
PRINT '' + @TYPE + @CAPACITY

CLOSE PRIMER_4

DEALLOCATE PRIMER_4; 



---------------------------------------
---------------BANK--------------------
---------------------------------------

USE BANK;
GO 

DECLARE @NAME NVARCHAR(20), @STAVKA NVARCHAR(20)
DECLARE PRIMER_BANK CURSOR GLOBAL STATIC SCROLL 
FOR SELECT Назаание_кредита,Ставка FROM БАНК


OPEN PRIMER_BANK
PRINT 'ВСЕ: '
FETCH PRIMER_BANK INTO @NAME, @STAVKA
WHILE @@FETCH_STATUS = 0
BEGIN
PRINT '' + @NAME + ' ' + @STAVKA
FETCH PRIMER_BANK INTO @NAME, @STAVKA
END
CLOSE PRIMER_BANK

OPEN PRIMER_BANK
PRINT 'ПЕРВАЯ СТРОКА: '
FETCH PRIMER_BANK INTO @NAME, @STAVKA
PRINT '' + @NAME + ' ' + @STAVKA

PRINT 'ПОСЛЕДНЯЯ СТРОКА: '
FETCH LAST FROM PRIMER_BANK INTO @NAME, @STAVKA
PRINT '' + @NAME + ' ' + @STAVKA

CLOSE PRIMER_BANK;

DEALLOCATE  PRIMER_BANK;


