@hostname=localhost
@port=7050
GET http://{{hostname}}:{{port}}/Start/Index
###
GET http://{{hostname}}:{{port}}/Start/One
###
GET http://{{hostname}}:{{port}}/Start/Two
###
GET http://{{hostname}}:{{port}}/Start/Three
###
POST http://{{hostname}}:{{port}}/Start/Index
###
POST http://{{hostname}}:{{port}}/Start/One
###
POST http://{{hostname}}:{{port}}/Start/Two
###
POST http://{{hostname}}:{{port}}/Start/Three
###